# Generated by Django 3.0.5 on 2020-08-27 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(2020, message='Год не может быть больше текущего')], verbose_name='Год публикации'),
        ),
    ]
