# Generated by Django 3.0.5 on 2020-08-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='yamdb.Title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Оценка'),
        ),
    ]
